### ISSUE TITLE
Error in coccoc-tokenizer/dicts/tokenizer/Freq2NontoneUniFile when installing on CentOS 7

### ISSUE THREAD

**Issue by TruongKhang** [coccoc/coccoc-tokenizer#6]
When I run the command: `make install`. The following errors are showed up:
![image](https://user-images.githubusercontent.com/18275776/61508883-306d9080-aa16-11e9-88a2-c8783a06c1de.png)

How to fix it? Please help me @bachan  @anhducle98 .

**Comment by kungfulon** [comment]
Make sure that you have permission on the installation directory. Commonly, if you don't set `CMAKE_INSTALL_PREFIX` then it will be installed to `/usr` iirc - in that case, use `sudo make install` should help.

**Comment by bachan** [comment]
This commit fixes it:
https://github.com/coccoc/coccoc-tokenizer/commit/208c47ac359a2e7cc5f732c93f6912665183f7ea

It's an issue with cmake 2.8 - in that version if an array is mentioned in a dependency list for a custom command in double quotes, then cmake would generate Makefile with a semi-colon separated list of all array elements (files, in this context) instead of putting one file per line into a resulted Makefile

later cmake versions fixed that issue, but centos7 distributive still uses 2.8.x
